// app/layout.tsx

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import ThemeProviderWrapper from '@/core/ThemeProviderWrapper';
import Header from '@/core/layout/Header';

const roboto = Roboto({
    weight: '400',
    subsets: ['vietnamese'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html lang='en'>
        <body className={`${roboto.className} bg-gray-100`}>
        <ThemeProviderWrapper>
           <Header />
            <main className='p-4'>
                {children}
            </main>
        </ThemeProviderWrapper>
        </body>
        </html>
    );
};

export default RootLayout;
