import { IScore } from '@/common/interfaces/score';

export const scores: IScore[] = [
    {
        "value": "Tin học đại cương",
        "key": null,
        "id": 1,
        "name": "Tin học đại cương",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 10,
        "scoreGK": 8,
        "scoreCK": 10,
        "scoreT10": 9.6,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Đại số",
        "key": null,
        "id": 2,
        "name": "Đại số",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 6,
        "scoreT10": 7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Tiếng Anh chuyên ngành 1 IT",
        "key": null,
        "id": 3,
        "name": "Tiếng Anh chuyên ngành 1 IT",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 6,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 5,
        "scoreT10": 5.6,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Cơ sở dữ liệu",
        "key": null,
        "id": 4,
        "name": "Cơ sở dữ liệu",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 6,
        "scoreCK": 6,
        "scoreT10": 6.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Tiếng Anh 1",
        "key": null,
        "id": 5,
        "name": "Tiếng Anh 1",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 8,
        "scoreBT": null,
        "scoreGK": 5.5,
        "scoreCK": 6,
        "scoreT10": 6.3,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Nhập môn ngành và kỹ năng mềm IT",
        "key": null,
        "id": 6,
        "name": "Nhập môn ngành và kỹ năng mềm IT",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": null,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 9,
        "scoreT10": 9,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Lập trình hướng đối tượng và Java cơ bản",
        "key": null,
        "id": 7,
        "name": "Lập trình hướng đối tượng và Java cơ bản",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 7,
        "scoreGK": 8,
        "scoreCK": 8.5,
        "scoreT10": 8.3,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2018-2019"
    },
    {
        "value": "Tiếng Anh chuyên ngành 2",
        "key": null,
        "id": 8,
        "name": "Tiếng Anh chuyên ngành 2",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 6,
        "scoreBT": null,
        "scoreGK": 8,
        "scoreCK": 5,
        "scoreT10": 5.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Đồ án cơ sở 1 (IT)",
        "key": null,
        "id": 9,
        "name": "Đồ án cơ sở 1 (IT)",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": null,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 5,
        "scoreT10": 5,
        "scoreCh": "D",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Nguyên lý hệ điều hành",
        "key": null,
        "id": 10,
        "name": "Nguyên lý hệ điều hành",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 6,
        "scoreCK": 6,
        "scoreT10": 6.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Kiến trúc máy tính",
        "key": null,
        "id": 11,
        "name": "Kiến trúc máy tính",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 8,
        "scoreBT": null,
        "scoreGK": 8,
        "scoreCK": 5,
        "scoreT10": 6.2,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Vật lý",
        "key": null,
        "id": 12,
        "name": "Vật lý",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 3.5,
        "scoreT10": 5.5,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Lập trình Java nâng cao",
        "key": null,
        "id": 13,
        "name": "Lập trình Java nâng cao",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 9,
        "scoreGK": 8,
        "scoreCK": 6,
        "scoreT10": 7.3,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Cấu trúc dữ liệu và giải thuật",
        "key": null,
        "id": 14,
        "name": "Cấu trúc dữ liệu và giải thuật",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 10,
        "scoreGK": 9,
        "scoreCK": 10,
        "scoreT10": 9.8,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Tiếng Anh 2",
        "key": null,
        "id": 15,
        "name": "Tiếng Anh 2",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": null,
        "scoreGK": 8,
        "scoreCK": 3,
        "scoreT10": 4.8,
        "scoreCh": "D",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Công nghệ Web",
        "key": null,
        "id": 16,
        "name": "Công nghệ Web",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 9.5,
        "scoreGK": 7,
        "scoreCK": 6.5,
        "scoreT10": 7.5,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2018-2019"
    },
    {
        "value": "Tiếng Anh chuyên ngành & thực hành 1",
        "key": null,
        "id": 17,
        "name": "Tiếng Anh chuyên ngành & thực hành 1",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 8,
        "scoreBT": null,
        "scoreGK": 6.5,
        "scoreCK": 5.5,
        "scoreT10": 6.2,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Mạng máy tính",
        "key": null,
        "id": 18,
        "name": "Mạng máy tính",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 7,
        "scoreGK": 6,
        "scoreCK": 6.5,
        "scoreT10": 6.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Chuyên đề 1 (IT)",
        "key": null,
        "id": 19,
        "name": "Chuyên đề 1 (IT)",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": null,
        "scoreBT": null,
        "scoreGK": 0,
        "scoreCK": 7,
        "scoreT10": 7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Phân tích và thiết kế hệ thống",
        "key": null,
        "id": 20,
        "name": "Phân tích và thiết kế hệ thống",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 6,
        "scoreBT": 7.5,
        "scoreGK": 6,
        "scoreCK": 7,
        "scoreT10": 6.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Toán rời rạc",
        "key": null,
        "id": 21,
        "name": "Toán rời rạc",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": 9,
        "scoreCK": 9,
        "scoreT10": 9,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Công nghệ web nâng cao",
        "key": null,
        "id": 22,
        "name": "Công nghệ web nâng cao",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 8,
        "scoreBT": 10,
        "scoreGK": 7,
        "scoreCK": 7,
        "scoreT10": 7.7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Tiếng Anh 3",
        "key": null,
        "id": 23,
        "name": "Tiếng Anh 3",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 4,
        "scoreCK": 5,
        "scoreT10": 5.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Hệ thống số",
        "key": null,
        "id": 24,
        "name": "Hệ thống số",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": null,
        "scoreGK": 8,
        "scoreCK": 7.5,
        "scoreT10": 7.5,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Đồ án cơ sở 2 (IT)",
        "key": null,
        "id": 25,
        "name": "Đồ án cơ sở 2 (IT)",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 9,
        "scoreT10": 8.4,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2019-2020"
    },
    {
        "value": "Lập trình di động",
        "key": null,
        "id": 26,
        "name": "Lập trình di động",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": 8,
        "scoreGK": 8,
        "scoreCK": 9,
        "scoreT10": 8.4,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2019-2020"
    },
    {
        "value": "Tiếng Anh chuyên ngành & thực hành 2",
        "key": null,
        "id": 27,
        "name": "Tiếng Anh chuyên ngành & thực hành 2",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 8,
        "scoreBT": null,
        "scoreGK": 9,
        "scoreCK": 7,
        "scoreT10": 7.6,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2019-2020"
    },
    {
        "value": "Công nghệ phần mềm",
        "key": null,
        "id": 28,
        "name": "Công nghệ phần mềm",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": 5,
        "scoreCK": 7.3,
        "scoreT10": 7.2,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2019-2020"
    },
    {
        "value": "Xác suất thống kê",
        "key": null,
        "id": 44,
        "name": "Xác suất thống kê",
        "countTC": 2,
        "countLH": 2,
        "scoreCC": 8,
        "scoreBT": 4,
        "scoreGK": 3,
        "scoreCK": 5.5,
        "scoreT10": 5,
        "scoreCh": "D",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Chuyên đề 2",
        "key": null,
        "id": 30,
        "name": "Chuyên đề 2",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": null,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 6.8,
        "scoreT10": 6.8,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2019-2020"
    },
    {
        "value": "Vi điều khiển",
        "key": null,
        "id": 31,
        "name": "Vi điều khiển",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": 7,
        "scoreGK": 7,
        "scoreCK": 7,
        "scoreT10": 7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2019-2020"
    },
    {
        "value": "Giải tích",
        "key": null,
        "id": 32,
        "name": "Giải tích",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 5.5,
        "scoreT10": 6.5,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2019-2020"
    },
    {
        "value": "Quản trị mạng",
        "key": null,
        "id": 33,
        "name": "Quản trị mạng",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 8.8,
        "scoreGK": 8.8,
        "scoreCK": 8,
        "scoreT10": 8.5,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Chuyên đề 3",
        "key": null,
        "id": 34,
        "name": "Chuyên đề 3",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 7.5,
        "scoreT10": 7.7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Trí tuệ nhân tạo",
        "key": null,
        "id": 35,
        "name": "Trí tuệ nhân tạo",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9.3,
        "scoreBT": 7.8,
        "scoreGK": 7,
        "scoreCK": 4.9,
        "scoreT10": 6.3,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Đồ họa máy tính",
        "key": null,
        "id": 36,
        "name": "Đồ họa máy tính",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 5,
        "scoreGK": 8,
        "scoreCK": 6,
        "scoreT10": 6.6,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Automat và Ngôn ngữ hình thức",
        "key": null,
        "id": 37,
        "name": "Automat và Ngôn ngữ hình thức",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 8.6,
        "scoreBT": null,
        "scoreGK": 9,
        "scoreCK": 6.5,
        "scoreT10": 7.4,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Lập trình mạng",
        "key": null,
        "id": 38,
        "name": "Lập trình mạng",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 7,
        "scoreGK": 8,
        "scoreCK": 10,
        "scoreT10": 8.9,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Quản lý dự án",
        "key": null,
        "id": 39,
        "name": "Quản lý dự án",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 8,
        "scoreT10": 8.2,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Đồ án cơ sở 4 (IT) !!",
        "key": null,
        "id": 40,
        "name": "Đồ án cơ sở 4 (IT) !!",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 5,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 6.5,
        "scoreT10": 6.1,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Thực tập doanh nghiệp IT !!",
        "key": null,
        "id": 41,
        "name": "Thực tập doanh nghiệp IT !!",
        "countTC": 1,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 9.5,
        "scoreT10": 9.4,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2020-2021"
    },
    {
        "value": "Chuyên đề 4",
        "key": null,
        "id": 42,
        "name": "Chuyên đề 4",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 8.5,
        "scoreCK": 8,
        "scoreT10": 8.5,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Bảo mật và An toàn hệ thống thông tin",
        "key": null,
        "id": 43,
        "name": "Bảo mật và An toàn hệ thống thông tin",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 7.3,
        "scoreGK": 9,
        "scoreCK": 7.8,
        "scoreT10": 8.1,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Kiểm thử phần mềm",
        "key": null,
        "id": 45,
        "name": "Kiểm thử phần mềm",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 6,
        "scoreGK": 7,
        "scoreCK": 4.25,
        "scoreT10": 5.6,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Xử lý tín hiệu số",
        "key": null,
        "id": 46,
        "name": "Xử lý tín hiệu số",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": 5,
        "scoreCK": 7.5,
        "scoreT10": 7.3,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Xử lý ảnh",
        "key": null,
        "id": 47,
        "name": "Xử lý ảnh",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 8,
        "scoreGK": 8,
        "scoreCK": null,
        "scoreT10": 4.2,
        "scoreCh": "D",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Trình biên dịch",
        "key": null,
        "id": 48,
        "name": "Trình biên dịch",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": null,
        "scoreGK": 4,
        "scoreCK": 7,
        "scoreT10": 6.4,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Kỹ thuật truyền số liệu",
        "key": null,
        "id": 49,
        "name": "Kỹ thuật truyền số liệu",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 9.6,
        "scoreCK": 8.3,
        "scoreT10": 8.9,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Đồ án cơ sở 3 IT",
        "key": null,
        "id": 50,
        "name": "Đồ án cơ sở 3 IT",
        "countTC": 2,
        "countLH": 2,
        "scoreCC": 5,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 8.75,
        "scoreT10": 7.6,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Đồ án cơ sở 5 IT",
        "key": null,
        "id": 51,
        "name": "Đồ án cơ sở 5 IT",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 7,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 7,
        "scoreT10": 7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2020-2021"
    },
    {
        "value": "Pháp luật đại cương",
        "key": null,
        "id": 52,
        "name": "Pháp luật đại cương",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 8,
        "scoreBT": null,
        "scoreGK": 6.8,
        "scoreCK": 3.8,
        "scoreT10": 5.3,
        "scoreCh": "D",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Triết học Mác - Lênin",
        "key": null,
        "id": 53,
        "name": "Triết học Mác - Lênin",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 9,
        "scoreCK": 6.5,
        "scoreT10": 7.7,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Tư tưởng Hồ Chí Minh",
        "key": null,
        "id": 54,
        "name": "Tư tưởng Hồ Chí Minh",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 9.5,
        "scoreCK": 4.2,
        "scoreT10": 6.4,
        "scoreCh": "C",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Thị giác máy tính",
        "key": null,
        "id": 55,
        "name": "Thị giác máy tính",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 7.5,
        "scoreGK": 10,
        "scoreCK": 8.5,
        "scoreT10": 8.8,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Chuyên đề 5 (IT)",
        "key": null,
        "id": 56,
        "name": "Chuyên đề 5 (IT)",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 8,
        "scoreGK": 7.5,
        "scoreCK": 9,
        "scoreT10": 8.6,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Xử lý ngôn ngữ tự nhiên",
        "key": null,
        "id": 57,
        "name": "Xử lý ngôn ngữ tự nhiên",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 6,
        "scoreGK": 9,
        "scoreCK": 8.9,
        "scoreT10": 8.5,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Đồ án chuyên ngành 1 (IT)",
        "key": null,
        "id": 58,
        "name": "Đồ án chuyên ngành 1 (IT)",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 10,
        "scoreT10": 10,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2021-2022"
    },
    {
        "value": "Chuyên đề 6 (IT)",
        "key": null,
        "id": 59,
        "name": "Chuyên đề 6 (IT)",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 8,
        "scoreGK": 8,
        "scoreCK": 8,
        "scoreT10": 8.2,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2021-2022"
    },
    {
        "value": "Mật mã học",
        "key": null,
        "id": 60,
        "name": "Mật mã học",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": 7.5,
        "scoreGK": 8.5,
        "scoreCK": 6.3,
        "scoreT10": 7.4,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2021-2022"
    },
    {
        "value": "Phân tích, thiết kế mạng",
        "key": null,
        "id": 61,
        "name": "Phân tích, thiết kế mạng",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": 8.2,
        "scoreGK": 8.5,
        "scoreCK": 8,
        "scoreT10": 8.2,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2021-2022"
    },
    {
        "value": "Lịch sử Đảng Cộng sản Việt Nam",
        "key": null,
        "id": 62,
        "name": "Lịch sử Đảng Cộng sản Việt Nam",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 9,
        "scoreCK": 6.6,
        "scoreT10": 7.8,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2021-2022"
    },
    {
        "value": "Kinh tế chính trị Mác - Lênin",
        "key": null,
        "id": 63,
        "name": "Kinh tế chính trị Mác - Lênin",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 6.8,
        "scoreCK": 2.5,
        "scoreT10": 4.9,
        "scoreCh": "D",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2021-2022"
    },
    {
        "value": "Đồ án chuyên ngành 2 IT",
        "key": null,
        "id": 64,
        "name": "Đồ án chuyên ngành 2 IT",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": 9,
        "scoreT10": 9,
        "scoreCh": "A",
        "scoreChChange": null,
        "semester": "Học kỳ 2 - 2021-2022"
    },
    {
        "value": "Chủ nghĩa xã hội khoa học",
        "key": null,
        "id": 65,
        "name": "Chủ nghĩa xã hội khoa học",
        "countTC": 2,
        "countLH": 1,
        "scoreCC": 10,
        "scoreBT": null,
        "scoreGK": 7,
        "scoreCK": 8,
        "scoreT10": 8.2,
        "scoreCh": "B",
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2022-2023"
    },
    {
        "value": "Thực tập tốt nghiệp (IT)",
        "key": null,
        "id": 66,
        "name": "Thực tập tốt nghiệp (IT)",
        "countTC": 3,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": null,
        "scoreT10": null,
        "scoreCh": null,
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2022-2023"
    },
    {
        "value": "Đồ án tốt nghiệp (IT) !!",
        "key": null,
        "id": 67,
        "name": "Đồ án tốt nghiệp (IT) !!",
        "countTC": 10,
        "countLH": 1,
        "scoreCC": 9,
        "scoreBT": null,
        "scoreGK": null,
        "scoreCK": null,
        "scoreT10": null,
        "scoreCh": null,
        "scoreChChange": null,
        "semester": "Học kỳ 1 - 2022-2023"
    }
]