import { IScore } from '@/common/interfaces/score';

const scores: IScore[] = [
    {
        value: 'A+',
        id: 1,
        name: 'Lập trình Python (Python Programming)',
        countTC: 3,
        countLH: 1,
        scoreCC: 10,
        scoreBT: 9,
        scoreGK: 9,
        scoreCK: 10,
        scoreT10: 9.5,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 2,
        name: 'Phát triển web (Web Development)',
        countTC: 3,
        countLH: 1,
        scoreCC: 8,
        scoreBT: 7,
        scoreGK: 7,
        scoreCK: 8,
        scoreT10: 7.5,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 3,
        name: 'Cơ sở dữ liệu (Database Systems)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 6,
        scoreGK: 7,
        scoreCK: 6,
        scoreT10: 6.5,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 4,
        name: 'Mạng máy tính (Computer Networks)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 6,
        scoreCK: 5,
        scoreT10: 5.5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 5,
        name: 'Lập trình Java (Java Programming)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 3,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
    {
        value: 'B',
        id: 6,
        name: 'An toàn thông tin (Information Security)',
        countTC: 3,
        countLH: 1,
        scoreCC: 8,
        scoreBT: 7,
        scoreGK: 7,
        scoreCK: 8,
        scoreT10: 7.5,
        scoreCh: 'B',
    },
    {
        value: 'A',
        id: 7,
        name: 'Khoa học dữ liệu (Data Science)',
        countTC: 3,
        countLH: 1,
        scoreCC: 9,
        scoreBT: 8,
        scoreGK: 9,
        scoreCK: 10,
        scoreT10: 9,
        scoreCh: 'A',
    },
    {
        value: 'C',
        id: 8,
        name: 'Trí tuệ nhân tạo (Artificial Intelligence)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 7,
        scoreGK: 7,
        scoreCK: 6,
        scoreT10: 6.5,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 9,
        name: 'Hệ thống nhúng (Embedded Systems)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 10,
        name: 'Lập trình C++ (C++ Programming)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 4,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
    {
        value: 'A',
        id: 11,
        name: 'Phân tích dữ liệu (Data Analysis)',
        countTC: 3,
        countLH: 1,
        scoreCC: 10,
        scoreBT: 9,
        scoreGK: 9,
        scoreCK: 9,
        scoreT10: 9.25,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 12,
        name: 'Kỹ thuật phần mềm (Software Engineering)',
        countTC: 3,
        countLH: 1,
        scoreCC: 7,
        scoreBT: 8,
        scoreGK: 7,
        scoreCK: 8,
        scoreT10: 7.5,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 13,
        name: 'Hệ điều hành (Operating Systems)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 6,
        scoreGK: 7,
        scoreCK: 6,
        scoreT10: 6.5,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 14,
        name: 'Phân tích thiết kế hệ thống (Systems Analysis and Design)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 15,
        name: 'Thuật toán (Algorithms)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 3,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 3.75,
        scoreCh: 'F',
    },
    {
        value: 'A',
        id: 16,
        name: 'Phân tích dữ liệu nâng cao (Advanced Data Analysis)',
        countTC: 3,
        countLH: 1,
        scoreCC: 10,
        scoreBT: 9,
        scoreGK: 10,
        scoreCK: 9,
        scoreT10: 9.5,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 17,
        name: 'Ứng dụng di động (Mobile Applications)',
        countTC: 3,
        countLH: 1,
        scoreCC: 8,
        scoreBT: 7,
        scoreGK: 8,
        scoreCK: 8,
        scoreT10: 7.75,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 18,
        name: 'Máy học (Machine Learning)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 7,
        scoreGK: 7,
        scoreCK: 6,
        scoreT10: 6.5,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 19,
        name: 'Phân tích yêu cầu phần mềm (Software Requirements Analysis)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 20,
        name: 'Lập trình Android (Android Programming)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 4,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
    {
        value: 'A',
        id: 21,
        name: 'Phân tích và thiết kế thuật toán (Algorithm Analysis and Design)',
        countTC: 3,
        countLH: 1,
        scoreCC: 9,
        scoreBT: 8,
        scoreGK: 9,
        scoreCK: 9,
        scoreT10: 8.75,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 22,
        name: 'Trí tuệ kinh doanh (Business Intelligence)',
        countTC: 3,
        countLH: 1,
        scoreCC: 8,
        scoreBT: 7,
        scoreGK: 8,
        scoreCK: 8,
        scoreT10: 7.75,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 23,
        name: 'Thiết kế giao diện người dùng (User Interface Design)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 7,
        scoreGK: 6,
        scoreCK: 6,
        scoreT10: 6.25,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 24,
        name: 'Kiểm thử phần mềm (Software Testing)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 25,
        name: 'Lập trình iOS (iOS Programming)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 4,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
    {
        value: 'A',
        id: 26,
        name: 'Công nghệ phần mềm (Software Technology)',
        countTC: 3,
        countLH: 1,
        scoreCC: 10,
        scoreBT: 9,
        scoreGK: 10,
        scoreCK: 10,
        scoreT10: 9.75,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 27,
        name: 'Phân tích dữ liệu với R (Data Analysis with R)',
        countTC: 3,
        countLH: 1,
        scoreCC: 7,
        scoreBT: 8,
        scoreGK: 8,
        scoreCK: 7,
        scoreT10: 7.5,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 28,
        name: 'Học sâu (Deep Learning)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 7,
        scoreGK: 6,
        scoreCK: 6,
        scoreT10: 6.25,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 29,
        name: 'Thiết kế hệ thống phần mềm (Software Systems Design)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 30,
        name: 'Hệ thống thông tin quản lý (Management Information Systems)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 4,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
    {
        value: 'A',
        id: 31,
        name: 'Phân tích dữ liệu lớn (Big Data Analytics)',
        countTC: 3,
        countLH: 1,
        scoreCC: 9,
        scoreBT: 9,
        scoreGK: 9,
        scoreCK: 9,
        scoreT10: 9,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 32,
        name: 'Khoa học máy tính (Computer Science)',
        countTC: 3,
        countLH: 1,
        scoreCC: 8,
        scoreBT: 7,
        scoreGK: 8,
        scoreCK: 8,
        scoreT10: 7.75,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 33,
        name: 'Lập trình web nâng cao (Advanced Web Development)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 7,
        scoreGK: 6,
        scoreCK: 6,
        scoreT10: 6.25,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 34,
        name: 'Điện toán đám mây (Cloud Computing)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 35,
        name: 'Quản trị cơ sở dữ liệu (Database Administration)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 4,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
    {
        value: 'A',
        id: 36,
        name: 'Phân tích mạng xã hội (Social Network Analysis)',
        countTC: 3,
        countLH: 1,
        scoreCC: 10,
        scoreBT: 9,
        scoreGK: 9,
        scoreCK: 9,
        scoreT10: 9.25,
        scoreCh: 'A',
    },
    {
        value: 'B',
        id: 37,
        name: 'An ninh mạng (Cybersecurity)',
        countTC: 3,
        countLH: 1,
        scoreCC: 8,
        scoreBT: 8,
        scoreGK: 8,
        scoreCK: 8,
        scoreT10: 8,
        scoreCh: 'B',
    },
    {
        value: 'C',
        id: 38,
        name: 'Phân tích thiết kế hệ thống thông tin (Information Systems Analysis and Design)',
        countTC: 3,
        countLH: 1,
        scoreCC: 6,
        scoreBT: 7,
        scoreGK: 6,
        scoreCK: 6,
        scoreT10: 6.25,
        scoreCh: 'C',
    },
    {
        value: 'D',
        id: 39,
        name: 'Phát triển ứng dụng web (Web Application Development)',
        countTC: 3,
        countLH: 1,
        scoreCC: 5,
        scoreBT: 5,
        scoreGK: 5,
        scoreCK: 5,
        scoreT10: 5,
        scoreCh: 'D',
    },
    {
        value: 'F',
        id: 40,
        name: 'Trí tuệ nhân tạo ứng dụng (Applied Artificial Intelligence)',
        countTC: 3,
        countLH: 1,
        scoreCC: 4,
        scoreBT: 4,
        scoreGK: 4,
        scoreCK: 4,
        scoreT10: 4,
        scoreCh: 'F',
    },
];

export default scores;
